version: '3.8'
name: calendar

services:
  calendar:
    container_name: calendar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5174:5173'
    volumes:
      - ../app:/usr/src/app/calendar
    working_dir: "/usr/src/app/calendar"
    tty: true
    environment:
      - WATCHPACK_POLLING=true